title: Coder Horse
email: contact@coder.horse
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://coder.horse" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  denikson

# Build settings
markdown: kramdown
remote_theme: denikson/coder-horse-jekyll
plugins:
  - jekyll-feed

